/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Chip-dependent power configuration and states.
 *
 * Copyright (C) 2022 Google LLC
 */

#ifndef __CALLISTO_CONFIG_PWR_STATE_H__
#define __CALLISTO_CONFIG_PWR_STATE_H__

enum aur_power_rate {
	AUR_OFF_RATE = 0,
	AUR_UUD_RATE = 178000,
	AUR_SUD_RATE = 355000,
	AUR_UD_RATE = 713000,
	AUR_NOM_RATE = 1065000,
	AUR_READY_RATE = AUR_UUD_RATE,
	AUR_UUD_PLUS_RATE = 256000,
	AUR_SUD_PLUS_RATE = 560000,
	AUR_UD_PLUS_RATE = 861000,
	AUR_PERCENT_FREQUENCY_5_RATE = AUR_UUD_RATE,
	AUR_PERCENT_FREQUENCY_10_RATE = AUR_UUD_RATE,
	AUR_PERCENT_FREQUENCY_15_RATE = AUR_UUD_RATE,
	AUR_PERCENT_FREQUENCY_20_RATE = AUR_UUD_RATE,
	AUR_PERCENT_FREQUENCY_25_RATE = AUR_UUD_RATE,
	AUR_PERCENT_FREQUENCY_30_RATE = AUR_UUD_RATE,
	AUR_PERCENT_FREQUENCY_35_RATE = AUR_UUD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_40_RATE = AUR_UUD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_45_RATE = AUR_UUD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_50_RATE = AUR_SUD_RATE,
	AUR_PERCENT_FREQUENCY_55_RATE = AUR_SUD_RATE,
	AUR_PERCENT_FREQUENCY_60_RATE = AUR_SUD_RATE,
	AUR_PERCENT_FREQUENCY_65_RATE = AUR_SUD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_70_RATE = AUR_SUD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_75_RATE = AUR_UD_RATE,
	AUR_PERCENT_FREQUENCY_80_RATE = AUR_UD_RATE,
	AUR_PERCENT_FREQUENCY_85_RATE = AUR_UD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_90_RATE = AUR_UD_PLUS_RATE,
	AUR_PERCENT_FREQUENCY_95_RATE = AUR_UD_PLUS_RATE,
	AUR_MAX_FREQUENCY_RATE = AUR_NOM_RATE,
	AUR_OVERDRIVE_FREQUENCY_RATE = AUR_NOM_RATE,
};

enum aur_mem_int_rate {
	AUR_MEM_INT_MIN = 0,
	AUR_MEM_INT_VERY_LOW = 0,
	AUR_MEM_INT_LOW = 356000,
	AUR_MEM_INT_HIGH = 664000,
	AUR_MEM_INT_VERY_HIGH = 799000,
	AUR_MEM_INT_MAX = 1066000,
};

enum aur_mem_mif_rate {
	AUR_MEM_MIF_MIN = 0,
	AUR_MEM_MIF_VERY_LOW = 0,
	AUR_MEM_MIF_LOW = 1014000,
	AUR_MEM_MIF_HIGH = 1352000,
	AUR_MEM_MIF_VERY_HIGH = 2028000,
	AUR_MEM_MIF_MAX = 3744000,
};

#endif /* __CALLISTO_CONFIG_PWR_STATE_H__ */
